version: '3.9'

services:
  internalapi:
    image: ${DOCKER_REGISTRY-}internalapi
    container_name: ${INTERNAL_API_CONTAINER_NAME}
    restart: unless-stopped
    ports:
        - "9980:${INTERNAL_API_CONTAINER_PORT}"
        - "5700:${INTERNAL_API_CONTAINER_GRPC_PORT}"
    healthcheck:
        test: curl --fail http://localhost:${INTERNAL_API_CONTAINER_PORT}/health || exit 1
        interval: 30s
        retries: 3
        start_period: 10s
        timeout: 10s
    volumes:
        - ${HOST_LOGS}/${INTERNAL_API_CONTAINER_NAME}/logs:${INTERNAL_API_CONTAINER_LOGS}
    environment:
        - ASPNETCORE_URLS=http://+:${INTERNAL_API_CONTAINER_PORT};http://+:${INTERNAL_API_CONTAINER_GRPC_PORT}
        - GrpcPort=${INTERNAL_API_CONTAINER_GRPC_PORT}
        - ApiPort=${INTERNAL_API_CONTAINER_PORT}
        - ConnectionStrings__Default=Host=${DATABASE_NAME};Port=${DATABASE_PORT};Database=${DATABASE_DB_NAME};Username=${DATABASE_USER};Password=${DATABASE_PASSWORD}
    build:
      context: .
      dockerfile: InternalApi/Dockerfile

  publicapi:
    image: ${DOCKER_REGISTRY-}publicapi
    container_name: ${PUBLIC_API_CONTAINER_NAME}
    restart: unless-stopped
    ports:
        - "9981:${PUBLIC_API_CONTAINER_PORT}"
    healthcheck:
        test: curl --fail http://localhost:${PUBLIC_API_CONTAINER_PORT}/health || exit 1
        interval: 30s
        retries: 3
        start_period: 10s
        timeout: 10s
    volumes:
        - ${HOST_LOGS}/${PUBLIC_API_CONTAINER_NAME}/logs:${PUBLIC_API_CONTAINER_LOGS}
    environment:
        - ASPNETCORE_URLS=http://+:${PUBLIC_API_CONTAINER_PORT}
        - GrpcServiceAddress=http://internal_api:${INTERNAL_API_CONTAINER_GRPC_PORT}
        - ConnectionStrings__Default=Host=${DATABASE_NAME};Port=${DATABASE_PORT};Database=${DATABASE_DB_NAME};Username=${DATABASE_USER};Password=${DATABASE_PASSWORD}
    build:
      context: .
      dockerfile: PublicApi/Dockerfile
  
  postgres:
    image: postgres:15.3
    container_name: ${DATABASE_CONTAINER_NAME}
    restart: unless-stopped
    environment:
        DATABASE_HOST: 127.0.0.1
        POSTGRES_USER: ${DATABASE_USER}
        POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
        POSTGRES_DB: ${DATABASE_CONTAINER_DB_NAME}
    ports:
        - "5432:${DATABASE_PORT}"
    volumes:
        - ${HOST_DATABASE_DATA}:${CONTAINER_DATABASE_DATA}
